In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,StandardScaler
df=pd.read_csv('data set/china_water_pollution_data (Logistic).csv')
df

FileNotFoundError: [Errno 2] No such file or directory: 'data set/china_water_pollution_data (Logistic).csv'

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Province                  3000 non-null   object 
 1   City                      3000 non-null   object 
 2   Monitoring_Station        3000 non-null   object 
 3   Latitude                  3000 non-null   float64
 4   Longitude                 3000 non-null   float64
 5   Date                      3000 non-null   object 
 6   Water_Temperature_C       3000 non-null   float64
 7   pH                        3000 non-null   float64
 8   Dissolved_Oxygen_mg_L     3000 non-null   float64
 9   Conductivity_uS_cm        3000 non-null   float64
 10  Turbidity_NTU             3000 non-null   float64
 11  Nitrate_mg_L              3000 non-null   float64
 12  Nitrite_mg_L              3000 non-null   float64
 13  Ammonia_N_mg_L            3000 non-null   float64
 14  Total_Ph

In [3]:
df.isnull().sum()

Province                      0
City                          0
Monitoring_Station            0
Latitude                      0
Longitude                     0
Date                          0
Water_Temperature_C           0
pH                            0
Dissolved_Oxygen_mg_L         0
Conductivity_uS_cm            0
Turbidity_NTU                 0
Nitrate_mg_L                  0
Nitrite_mg_L                  0
Ammonia_N_mg_L                0
Total_Phosphorus_mg_L         0
Total_Nitrogen_mg_L           0
COD_mg_L                      0
BOD_mg_L                      0
Heavy_Metals_Pb_ug_L          0
Heavy_Metals_Cd_ug_L          0
Heavy_Metals_Hg_ug_L          0
Coliform_Count_CFU_100mL      0
Water_Quality_Index           0
Pollution_Level               0
Remarks                     752
dtype: int64

In [4]:
le=LabelEncoder()
df['Province']=le.fit_transform(df['Province'])
df['City']=le.fit_transform(df['City'])
df['Monitoring_Station']=le.fit_transform(df['Monitoring_Station'])
df['Date']=le.fit_transform(df['Date'])
df['Pollution_Level']=le.fit_transform(df['Pollution_Level'])
df['Remarks']=le.fit_transform(df['Remarks'])

In [5]:
df['Remarks']=df['Remarks'].fillna(df['Remarks'].mode()[0])

In [6]:
x=df.drop('Remarks',axis=1)
y=df['Remarks']

In [ ]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()
x=ms.fit_transform(x)

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.27666666666666667
[[43 25 32 44]
 [44 33 36 56]
 [38 19 43 39]
 [39 18 44 47]]
              precision    recall  f1-score   support

           0       0.26      0.30      0.28       144
           1       0.35      0.20      0.25       169
           2       0.28      0.31      0.29       139
           3       0.25      0.32      0.28       148

    accuracy                           0.28       600
   macro avg       0.28      0.28      0.28       600
weighted avg       0.29      0.28      0.27       600



In [10]:
from sklearn.naive_bayes import BernoulliNB
nb=BernoulliNB()
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.24833333333333332
[[130   0   1  13]
 [147   0   1  21]
 [129   0   0  10]
 [129   0   0  19]]
              precision    recall  f1-score   support

           0       0.24      0.90      0.38       144
           1       0.00      0.00      0.00       169
           2       0.00      0.00      0.00       139
           3       0.30      0.13      0.18       148

    accuracy                           0.25       600
   macro avg       0.14      0.26      0.14       600
weighted avg       0.13      0.25      0.14       600



C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capi

In [1]:
from sklearn.naive_bayes import BernoulliNB
nb=BernoulliNB()
nb.fit(x_test,y_test)
y_pred=nb.predict(x_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

NameError: name 'x_test' is not defined

In [11]:
from sklearn.naive_bayes import MultinomialNB
mb=MultinomialNB()
mb.fit(x_train,y_train)
y_pred=nb.predict(x_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.24833333333333332
[[130   0   1  13]
 [147   0   1  21]
 [129   0   0  10]
 [129   0   0  19]]
              precision    recall  f1-score   support

           0       0.24      0.90      0.38       144
           1       0.00      0.00      0.00       169
           2       0.00      0.00      0.00       139
           3       0.30      0.13      0.18       148

    accuracy                           0.25       600
   macro avg       0.14      0.26      0.14       600
weighted avg       0.13      0.25      0.14       600



C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capi

In [12]:
from sklearn.naive_bayes import ComplementNB
cb=ComplementNB()
cb.fit(x_train,y_train)
y_pred=nb.predict(x_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.24833333333333332
[[130   0   1  13]
 [147   0   1  21]
 [129   0   0  10]
 [129   0   0  19]]
              precision    recall  f1-score   support

           0       0.24      0.90      0.38       144
           1       0.00      0.00      0.00       169
           2       0.00      0.00      0.00       139
           3       0.30      0.13      0.18       148

    accuracy                           0.25       600
   macro avg       0.14      0.26      0.14       600
weighted avg       0.13      0.25      0.14       600



C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capi

In [13]:
from sklearn.naive_bayes import BernoulliNB
nb=BernoulliNB(alpha=1.0,fit_prior=True,class_prior=None,force_alpha=True)
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.24833333333333332
[[130   0   1  13]
 [147   0   1  21]
 [129   0   0  10]
 [129   0   0  19]]
              precision    recall  f1-score   support

           0       0.24      0.90      0.38       144
           1       0.00      0.00      0.00       169
           2       0.00      0.00      0.00       139
           3       0.30      0.13      0.18       148

    accuracy                           0.25       600
   macro avg       0.14      0.26      0.14       600
weighted avg       0.13      0.25      0.14       600



C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capi

In [14]:
from sklearn.naive_bayes import MultinomialNB
mb=MultinomialNB(alpha=2.5,fit_prior=True)
mb.fit(x_train,y_train)
y_pred=nb.predict(x_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.24833333333333332
[[130   0   1  13]
 [147   0   1  21]
 [129   0   0  10]
 [129   0   0  19]]
              precision    recall  f1-score   support

           0       0.24      0.90      0.38       144
           1       0.00      0.00      0.00       169
           2       0.00      0.00      0.00       139
           3       0.30      0.13      0.18       148

    accuracy                           0.25       600
   macro avg       0.14      0.26      0.14       600
weighted avg       0.13      0.25      0.14       600



C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capi

In [15]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB(var_smoothing=10,priors=None)
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.24
[[144   0   0   0]
 [169   0   0   0]
 [139   0   0   0]
 [148   0   0   0]]
              precision    recall  f1-score   support

           0       0.24      1.00      0.39       144
           1       0.00      0.00      0.00       169
           2       0.00      0.00      0.00       139
           3       0.00      0.00      0.00       148

    accuracy                           0.24       600
   macro avg       0.06      0.25      0.10       600
weighted avg       0.06      0.24      0.09       600



C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capi

In [24]:
from sklearn.naive_bayes import ComplementNB
cb=ComplementNB(alpha=0.1,fit_prior=True,class_prior=None,force_alpha=False,norm=False)
cb.fit(x_train,y_train)
y_pred=nb.predict(x_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.24
[[144   0   0   0]
 [169   0   0   0]
 [139   0   0   0]
 [148   0   0   0]]
              precision    recall  f1-score   support

           0       0.24      1.00      0.39       144
           1       0.00      0.00      0.00       169
           2       0.00      0.00      0.00       139
           3       0.00      0.00      0.00       148

    accuracy                           0.24       600
   macro avg       0.06      0.25      0.10       600
weighted avg       0.06      0.24      0.09       600



C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capi