In [1]:
import numpy as np
a=np.arange(0,18)
b=np.arange(20,38)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]


In [2]:
np.add(a,b)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54])

In [3]:
np.subtract(a,b)

array([-20, -20, -20, -20, -20, -20, -20, -20, -20, -20, -20, -20, -20,
       -20, -20, -20, -20, -20])

In [4]:
np.multiply(a,b)

array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261, 300, 341, 384,
       429, 476, 525, 576, 629])

In [5]:
np.divide(a,b)

array([0.        , 0.04761905, 0.09090909, 0.13043478, 0.16666667,
       0.2       , 0.23076923, 0.25925926, 0.28571429, 0.31034483,
       0.33333333, 0.35483871, 0.375     , 0.39393939, 0.41176471,
       0.42857143, 0.44444444, 0.45945946])

In [6]:
np.sum(a)

np.int64(153)

In [7]:
np.sum(b)

np.int64(513)

In [8]:
np.sum(a,axis=0)

np.int64(153)

In [9]:
np.mean(b)

np.float64(28.5)

In [10]:
#np.std(a)
np.median(b)

np.float64(28.5)

In [11]:
from scipy import stats
#stats.mode(a)
stats.mode(b)
#print(np.median(a))
#stats.mode(df['marks'])

ModeResult(mode=np.int64(20), count=np.int64(1))

In [16]:
x="my name is"
y="saranya"
print(x,y)
print(np.char.add(x,y))
print(np.char.upper(x), np.char.upper(y))
print(np.char.lower(x), np.char.lower(y))
print(np.char.split(x))
print(np.char.split(y))
print(np.char.center(x,40,fillchar="*"))
print(np.char.center(y,40,fillchar="*"))
print(np.char.replace(x, "name", "age"))
print(np.char.replace(y, "saranya", "21"))

my name is saranya
my name issaranya
MY NAME IS SARANYA
my name is saranya
['my', 'name', 'is']
['saranya']
***************my name is***************
****************saranya*****************
my age is
21
