In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,StandardScaler
df=pd.read_csv(r'C:\Users\Lenovo\Downloads\data set\china_water_pollution_data (Logistic).csv')
df

Province      City  Monitoring_Station   Latitude   Longitude  \
0      Zhejiang    Ningbo    Ningbo_Station_2  25.523836  122.622036   
1       Sichuan  Mianyang  Mianyang_Station_1  32.243099  112.888760   
2      Zhejiang    Ningbo    Ningbo_Station_8  29.996179  124.744859   
3       Beijing   Beijing  Beijing_Station_10  29.976437  118.274846   
4       Sichuan   Chengdu   Chengdu_Station_1  43.524720  121.666111   
...         ...       ...                 ...        ...         ...   
2995   Shandong   Qingdao   Qingdao_Station_6  28.766067  100.662530   
2996  Guangdong  Shenzhen  Shenzhen_Station_3  34.608605  121.475802   
2997   Shandong     Jinan     Jinan_Station_1  36.642090  102.593904   
2998    Sichuan   Chengdu   Chengdu_Station_4  25.261258  119.203392   
2999     Yunnan   Kunming   Kunming_Station_5  24.071840  117.344491   

            Date  Water_Temperature_C    pH  Dissolved_Oxygen_mg_L  \
0     2023-06-01                22.48  6.93                   9.30   
1     2023-03-05                27.33  6.89                   8.14   
2     2023-07-13                21.04  6.02                   5.34   
3     2023-02-17                16.62  7.31                  10.06   
4     2023-03-06                21.81  7.77                   7.93   
...          ...                  ...   ...                    ...   
2995  2023-11-03                14.26  6.68                   8.83   
2996  2023-07-22                22.29  7.26                   8.89   
2997  2023-06-29                26.02  6.08                   6.91   
2998  2023-01-10                22.64  6.77                   8.11   
2999  2023-03-02                21.25  6.59                   5.61   

      Conductivity_uS_cm  ...  Total_Nitrogen_mg_L  COD_mg_L  BOD_mg_L  \
0                 652.30  ...                 2.71     15.38      1.39   
1                 357.53  ...                 3.15     16.82      2.98   
2                 519.69  ...                 3.39     17.31      2.65   
3                 593.13  ...                 2.91     17.95      5.18   
4                 656.46  ...                 3.45     20.10      3.47   
...                  ...  ...                  ...       ...       ...   
2995              465.49  ...                 3.34     13.18      2.32   
2996              606.39  ...                 3.66     18.86      4.40   
2997              378.42  ...                 2.35     20.42      4.58   
2998              462.59  ...                 2.73     21.58      3.50   
2999              529.35  ...                 2.04     21.23      3.18   

      Heavy_Metals_Pb_ug_L  Heavy_Metals_Cd_ug_L  Heavy_Metals_Hg_ug_L  \
0                     6.90                  0.66                  0.02   
1                     4.68                  0.39                  0.10   
2                     3.24                  0.27                  0.11   
3                     3.20                  0.67                  0.11   
4                     2.01                  0.34                  0.14   
...                    ...                   ...                   ...   
2995                  5.61                  0.49                  0.11   
2996                  5.70                  0.53                  0.19   
2997                  5.55                  0.62                  0.05   
2998                 -1.55                  0.44                  0.06   
2999                  5.49                  0.45                  0.06   

      Coliform_Count_CFU_100mL  Water_Quality_Index  Pollution_Level  \
0                           87                36.64        Very Poor   
1                          116                66.25        Excellent   
2                          110                98.69             Poor   
3                           99                71.32             Poor   
4                           82                16.12        Excellent   
...                        ...                  ...              ...   
2995               

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Province                  3000 non-null   object 
 1   City                      3000 non-null   object 
 2   Monitoring_Station        3000 non-null   object 
 3   Latitude                  3000 non-null   float64
 4   Longitude                 3000 non-null   float64
 5   Date                      3000 non-null   object 
 6   Water_Temperature_C       3000 non-null   float64
 7   pH                        3000 non-null   float64
 8   Dissolved_Oxygen_mg_L     3000 non-null   float64
 9   Conductivity_uS_cm        3000 non-null   float64
 10  Turbidity_NTU             3000 non-null   float64
 11  Nitrate_mg_L              3000 non-null   float64
 12  Nitrite_mg_L              3000 non-null   float64
 13  Ammonia_N_mg_L            3000 non-null   float64
 14  Total_Ph

In [5]:
df.isnull().sum()

Province                      0
City                          0
Monitoring_Station            0
Latitude                      0
Longitude                     0
Date                          0
Water_Temperature_C           0
pH                            0
Dissolved_Oxygen_mg_L         0
Conductivity_uS_cm            0
Turbidity_NTU                 0
Nitrate_mg_L                  0
Nitrite_mg_L                  0
Ammonia_N_mg_L                0
Total_Phosphorus_mg_L         0
Total_Nitrogen_mg_L           0
COD_mg_L                      0
BOD_mg_L                      0
Heavy_Metals_Pb_ug_L          0
Heavy_Metals_Cd_ug_L          0
Heavy_Metals_Hg_ug_L          0
Coliform_Count_CFU_100mL      0
Water_Quality_Index           0
Pollution_Level               0
Remarks                     752
dtype: int64

In [6]:
le=LabelEncoder()
df['Province']=le.fit_transform(df['Province'])
df['City']=le.fit_transform(df['City'])
df['Monitoring_Station']=le.fit_transform(df['Monitoring_Station'])
df['Date']=le.fit_transform(df['Date'])
df['Pollution_Level']=le.fit_transform(df['Pollution_Level'])
df['Remarks']=le.fit_transform(df['Remarks'])

In [7]:
df['Remarks']=df['Remarks'].fillna(df['Remarks'].mode()[0])

In [8]:
df=df.drop(['Date'],axis=1)

In [10]:
df['Remarks'].value_counts()

Remarks
0    780
3    752
1    745
2    723
Name: count, dtype: int64

In [11]:
from imblearn.over_sampling import SMOTE
x=df.drop(columns="Remarks",axis=1)
y=df["Remarks"]
smote=SMOTE(sampling_strategy="minority")
x_sm,y_sm=smote.fit_resample(x,y)
print(x_sm.shape)
print(y_sm.shape)

(3057, 23)
(3057,)


In [12]:
x=df.drop('Remarks',axis=1)
y=df['Remarks']
from sklearn.preprocessing import MinMaxScaler
mn=MinMaxScaler()
x=mn.fit_transform(x)

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.30, random_state=42)
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.2688888888888889
              precision    recall  f1-score   support

           0       0.28      0.36      0.31       232
           1       0.30      0.19      0.23       237
           2       0.27      0.22      0.24       213
           3       0.24      0.30      0.27       218

    accuracy                           0.27       900
   macro avg       0.27      0.27      0.26       900
weighted avg       0.27      0.27      0.26       900

[[84 37 40 71]
 [81 45 35 76]
 [69 39 47 58]
 [71 30 51 66]]


In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.30, random_state=42)
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_test,y_test)
y_pred=model.predict(x_test)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.3466666666666667
              precision    recall  f1-score   support

           0       0.32      0.33      0.32       232
           1       0.36      0.46      0.40       237
           2       0.36      0.37      0.36       213
           3       0.34      0.23      0.27       218

    accuracy                           0.35       900
   macro avg       0.35      0.34      0.34       900
weighted avg       0.35      0.35      0.34       900

[[ 76  75  44  37]
 [ 54 108  43  32]
 [ 51  56  78  28]
 [ 57  61  50  50]]


In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.30, random_state=42)
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.26
              precision    recall  f1-score   support

           0       0.25      0.31      0.28       232
           1       0.30      0.24      0.27       237
           2       0.26      0.22      0.24       213
           3       0.24      0.28      0.26       218

    accuracy                           0.26       900
   macro avg       0.26      0.26      0.26       900
weighted avg       0.26      0.26      0.26       900

[[72 52 51 57]
 [71 56 40 70]
 [71 35 46 61]
 [76 42 40 60]]


In [16]:
model.fit(x_test,y_test)
y_pred=model.predict(x_test)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       232
           1       1.00      1.00      1.00       237
           2       1.00      1.00      1.00       213
           3       1.00      1.00      1.00       218

    accuracy                           1.00       900
   macro avg       1.00      1.00      1.00       900
weighted avg       1.00      1.00      1.00       900

[[232   0   0   0]
 [  0 237   0   0]
 [  0   0 213   0]
 [  0   0   0 218]]
