In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("imdb_movies.csv")
df.head(5)

names       date_x  score  \
0                    Creed III  03/02/2023    73.0   
1     Avatar: The Way of Water  12/15/2022    78.0   
2  The Super Mario Bros. Movie  04/05/2023    76.0   
3                      Mummies  01/05/2023    70.0   
4                    Supercell  03/17/2023    61.0   

                                           genre  \
0                                  Drama, Action   
1             Science Fiction, Adventure, Action   
2  Animation, Adventure, Family, Fantasy, Comedy   
3  Animation, Comedy, Family, Adventure, Fantasy   
4                                         Action   

                                            overview  \
0  After dominating the boxing world, Adonis Cree...   
1  Set more than a decade after the events of the...   
2  While working underground to fix a water main,...   
3  Through a series of unfortunate events, three ...   
4  Good-hearted teenager William always lived in ...   

                                                crew  \
0  Michael B. Jordan, Adonis Creed, Tessa Thompso...   
1  Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...   
2  Chris Pratt, Mario (voice), Anya Taylor-Joy, P...   
3  Óscar Barberán, Thut (voice), Ana Esther Albor...   
4  Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...   

                    orig_title     status            orig_lang     budget_x  \
0                    Creed III   Released              English   75000000.0   
1     Avatar: The Way of Water   Released              English  460000000.0   
2  The Super Mario Bros. Movie   Released              English  100000000.0   
3                       Momias   Released   Spanish, Castilian   12300000.0   
4                    Supercell   Released              English   77000000.0   

        revenue country  
0  2.716167e+08      AU  
1  2.316795e+09      AU  
2  7.244590e+08      AU  
3  3.420000e+07      AU  
4  3.409420e+08      US

In [3]:
df.columns

Index(['names', 'date_x', 'score', 'genre', 'overview', 'crew', 'orig_title',
       'status', 'orig_lang', 'budget_x', 'revenue', 'country'],
      dtype='object')

In [4]:
df.shape

(10178, 12)

In [5]:
df.drop(['crew'],axis=1,inplace=True)
df.head(2)

names       date_x  score  \
0                 Creed III  03/02/2023    73.0   
1  Avatar: The Way of Water  12/15/2022    78.0   

                                genre  \
0                       Drama, Action   
1  Science Fiction, Adventure, Action   

                                            overview  \
0  After dominating the boxing world, Adonis Cree...   
1  Set more than a decade after the events of the...   

                 orig_title     status orig_lang     budget_x       revenue  \
0                 Creed III   Released   English   75000000.0  2.716167e+08   
1  Avatar: The Way of Water   Released   English  460000000.0  2.316795e+09   

  country  
0      AU  
1      AU

In [6]:
df.rename(columns={"names":"movie_name"},inplace=True)
df.head(2)

movie_name       date_x  score  \
0                 Creed III  03/02/2023    73.0   
1  Avatar: The Way of Water  12/15/2022    78.0   

                                genre  \
0                       Drama, Action   
1  Science Fiction, Adventure, Action   

                                            overview  \
0  After dominating the boxing world, Adonis Cree...   
1  Set more than a decade after the events of the...   

                 orig_title     status orig_lang     budget_x       revenue  \
0                 Creed III   Released   English   75000000.0  2.716167e+08   
1  Avatar: The Way of Water   Released   English  460000000.0  2.316795e+09   

  country  
0      AU  
1      AU

In [7]:
df.isnull().sum()

movie_name     0
date_x         0
score          0
genre         85
overview       0
orig_title     0
status         0
orig_lang      0
budget_x       0
revenue        0
country        0
dtype: int64

In [8]:
df['genre']=df['genre'].fillna(df['genre'].mode()[0])
df.isnull().sum()

movie_name    0
date_x        0
score         0
genre         0
overview      0
orig_title    0
status        0
orig_lang     0
budget_x      0
revenue       0
country       0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10178 entries, 0 to 10177
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   movie_name  10178 non-null  object 
 1   date_x      10178 non-null  object 
 2   score       10178 non-null  float64
 3   genre       10178 non-null  object 
 4   overview    10178 non-null  object 
 5   orig_title  10178 non-null  object 
 6   status      10178 non-null  object 
 7   orig_lang   10178 non-null  object 
 8   budget_x    10178 non-null  float64
 9   revenue     10178 non-null  float64
 10  country     10178 non-null  object 
dtypes: float64(3), object(8)
memory usage: 874.8+ KB


In [15]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['movie_name']=le.fit_transform(df['movie_name'])
df['date_x']=le.fit_transform(df['date_x'])
df['genre']=le.fit_transform(df['genre'])
df['overview']=le.fit_transform(df['overview'])
df['orig_title']=le.fit_transform(df['orig_title'])
df['status']=le.fit_transform(df['status'])
df['orig_lang']=le.fit_transform(df['orig_lang'])
df['country']=le.fit_transform(df['country'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10178 entries, 0 to 10177
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   movie_name  10178 non-null  int64  
 1   date_x      10178 non-null  int64  
 2   score       10178 non-null  float64
 3   genre       10178 non-null  int64  
 4   overview    10178 non-null  int64  
 5   orig_title  10178 non-null  int64  
 6   status      10178 non-null  int64  
 7   orig_lang   10178 non-null  int64  
 8   budget_x    10178 non-null  float64
 9   revenue     10178 non-null  float64
 10  country     10178 non-null  int64  
dtypes: float64(3), int64(8)
memory usage: 874.8 KB


In [16]:
x=df.drop(['movie_name'],axis=1)
y=df['movie_name']

In [17]:
movieMatrix= np.ndarray(
    shape=(np.max(df.movie_name.values),np.max(df.genre.values)),
    dtype=np.uint8)
movieMatrix[df.movie_name.values-1,df.genre.values-1]=df.score.values
print(movieMatrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x).T
x

array([[-1.14264963e+00,  1.56282742e+00, -8.24963330e-01, ...,
         1.62575956e+00,  4.65175337e-03,  8.27118159e-02],
       [ 7.02031892e-01,  1.07140776e+00,  9.23657411e-01, ...,
        -1.84470183e-01, -6.27721220e-01,  4.80406374e-01],
       [ 5.72292111e-02,  1.38141380e+00, -8.04133581e-01, ...,
         4.07559600e-01, -1.70727890e+00, -5.87185863e-01],
       ...,
       [ 1.77275581e-01,  6.92304101e+00,  6.15312297e-01, ...,
        -7.54866551e-01,  8.95655796e-01,  4.82149135e-01],
       [ 6.65164769e-02,  7.42924764e+00,  1.69676880e+00, ...,
        -8.28521634e-01,  8.01086101e-01,  1.03055481e+00],
       [-8.89691945e-01, -8.89691945e-01, -8.89691945e-01, ...,
         1.43178282e+00,  1.43178282e+00, -1.45067965e-01]],
      shape=(10, 10178))

In [33]:
A=x.T/np.sqrt(movieMatrix.shape[1]-1)
U,S,V= np.linalg.svd(A)

In [34]:
def similar(df,movie_name,top_n):
    index= movie_name -1
    movie_row= df[index,:]
    magnitude= np.sqrt(np.einsum('ij, ij -> i',df,df))
    similarity= np.dot(movie_row,df.T) / (magnitude[index]*magnitude)
    sort_indexes= np.argsort(-similarity)
    return sort_indexes[:top_n]

In [45]:
k=40
genre=9
top_n=10
sliced=V.T[:,:k]
indexes=similar(sliced,genre,top_n)
print('Recommendation for movie {0}: \n'.format(
 df[df.genre == genre].orig_title.values[0]))  
for name in  indexes + 1:
    print( df[df.genre == genre].orig_title.values[0])

Recommendation for movie 1241: 

1241
1241
1241
1241
1241
1241
1241
1241
1241
1241
