In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,StandardScaler
df=pd.read_csv('student-mat.csv')
df

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0       GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1       GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2       GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3       GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4       GP   F   16       U     GT3       T  ...     2       5        4   6  10  10
..     ...  ..  ...     ...     ...     ...  ...   ...     ...      ...  ..  ..  ..
390     MS   M   20       U     LE3       A  ...     5       4       11   9   9   9
391     MS   M   17       U     LE3       T  ...     4       2        3  14  16  16
392     MS   M   21       R     GT3       T  ...     3       3        3  10   8   7
393     MS   M   18       R     LE3       T  ...     4       5        0  11  12  10
394     MS   M   19       U     LE3       T  ...     3       5        5   8   9   9

[395 rows x 33 columns]

In [3]:
df.shape

(395, 33)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    int64
 1   sex         395 non-null    int64
 2   age         395 non-null    int64
 3   address     395 non-null    int64
 4   famsize     395 non-null    int64
 5   Pstatus     395 non-null    int64
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    int64
 9   Fjob        395 non-null    int64
 10  reason      395 non-null    int64
 11  guardian    395 non-null    int64
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    int64
 16  famsup      395 non-null    int64
 17  paid        395 non-null    int64
 18  activities  395 non-null    int64
 19  nursery     395 non-null    int64
 20  higher      395 non-null    int6

In [4]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [5]:
le=LabelEncoder()
df['school']=le.fit_transform(df['school'])
df['sex']=le.fit_transform(df['sex'])
df['address']=le.fit_transform(df['address'])
df['famsize']=le.fit_transform(df['famsize'])
df['Pstatus']=le.fit_transform(df['Pstatus'])
df['Mjob']=le.fit_transform(df['Mjob'])
df['Fjob']=le.fit_transform(df['Fjob'])
df['reason']=le.fit_transform(df['reason'])
df['guardian']=le.fit_transform(df['guardian'])
df['schoolsup']=le.fit_transform(df['schoolsup'])
df['famsup']=le.fit_transform(df['famsup'])
df['paid']=le.fit_transform(df['paid'])
df['activities']=le.fit_transform(df['activities'])
df['nursery']=le.fit_transform(df['nursery'])
df['higher']=le.fit_transform(df['higher'])
df['internet']=le.fit_transform(df['internet'])
df['romantic']=le.fit_transform(df['romantic'])


In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.corr()

school       sex       age  ...        G1        G2        G3
school      1.000000 -0.012286  0.377610  ... -0.025731 -0.050086 -0.045017
sex        -0.012286  1.000000 -0.028606  ...  0.091839  0.091099  0.103456
age         0.377610 -0.028606  1.000000  ... -0.064081 -0.143474 -0.161579
address    -0.279797 -0.028504 -0.146722  ...  0.069704  0.126037  0.105756
famsize     0.064866  0.089862  0.037847  ...  0.071445  0.081223  0.081407
Pstatus     0.045923  0.023443  0.029598  ... -0.016868 -0.041382 -0.058009
Medu       -0.133333  0.078228 -0.163658  ...  0.205341  0.215527  0.217147
Fedu       -0.079807  0.034878 -0.163438  ...  0.190270  0.164893  0.152457
Mjob       -0.056670  0.191421 -0.069104  ...  0.081674  0.097390  0.102082
Fjob        0.018974  0.084957 -0.035191  ...  0.057661  0.067006  0.042286
reason     -0.090010 -0.095867 -0.015337  ...  0.099491  0.117775  0.121994
guardian    0.011109 -0.071343  0.290485  ... -0.041727 -0.087495 -0.070109
traveltime  0.242308  0.059722  0.070641  ... -0.093040 -0.153198 -0.117142
studytime  -0.090681 -0.306268 -0.004140  ...  0.160612  0.135880  0.097820
failures    0.059804  0.044436  0.243665  ... -0.354718 -0.355896 -0.360415
schoolsup  -0.139789 -0.138271 -0.251811  ... -0.212607 -0.117385 -0.082788
famsup     -0.164967 -0.151623 -0.140609  ... -0.084569 -0.059166 -0.039157
paid       -0.017083 -0.129126 -0.035933  ...  0.039079  0.105198  0.101996
activities -0.116946  0.099833 -0.103063  ...  0.057010  0.050552  0.016100
nursery    -0.089277 -0.008203 -0.086632  ...  0.069263  0.068146  0.051568
higher     -0.024150 -0.151056 -0.209081  ...  0.178264  0.179129  0.182465
internet   -0.133578  0.044113 -0.112094  ...  0.071619  0.119439  0.098483
romantic    0.060700 -0.102023  0.164669  ... -0.037188 -0.111774 -0.129970
famrel     -0.047926  0.058971  0.053940  ...  0.022168 -0.018281  0.051363
freetime    0.032988  0.238744  0.016434  ...  0.012613 -0.013777  0.011307
goout      -0.007152  0.075897  0.126964  ... -0.149104 -0.162250 -0.132791
Dalc        0.114209  0.268171  0.131125  ... -0.094159 -0.064120 -0.054660
Walc        0.065087  0.274194  0.117276  ... -0.126179 -0.084927 -0.051939
health     -0.042651  0.143588 -0.062187  ... -0.073172 -0.097720 -0.061335
absences   -0.088480 -0.066962  0.175230  ... -0.031003 -0.031777  0.034247
G1         -0.025731  0.091839 -0.064081  ...  1.000000  0.852118  0.801468
G2         -0.050086  0.091099 -0.143474  ...  0.852118  1.000000  0.904868
G3         -0.045017  0.103456 -0.161579  ...  0.801468  0.904868  1.000000

[33 rows x 33 columns]

In [ ]:
x=df.drop('studytime',axis=1)
y=df['studytime']

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.43037974683544306


In [13]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.32      0.35      0.33        23
           2       0.51      0.57      0.54        40
           3       0.33      0.30      0.32        10
           4       0.00      0.00      0.00         6

    accuracy                           0.43        79
   macro avg       0.29      0.31      0.30        79
weighted avg       0.39      0.43      0.41        79



C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capi

In [14]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[ 8 13  2  0]
 [13 23  4  0]
 [ 2  5  3  0]
 [ 2  4  0  0]]


In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_test,y_test)
y_pred=knn.predict(x_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.620253164556962


In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.54      0.57      0.55        23
           2       0.67      0.75      0.71        40
           3       0.56      0.50      0.53        10
           4       1.00      0.17      0.29         6

    accuracy                           0.62        79
   macro avg       0.69      0.50      0.52        79
weighted avg       0.64      0.62      0.61        79



In [17]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[13  8  2  0]
 [ 8 30  2  0]
 [ 2  3  5  0]
 [ 1  4  0  1]]


In [18]:
from sklearn.model_selection import KFold,cross_val_score
k=5
KF=KFold(n_splits=k,random_state=42,shuffle=True)
score=cross_val_score(knn,x,y,cv=KF)
print(score)
print(score.mean())                       

[0.43037975 0.49367089 0.5443038  0.49367089 0.48101266]
0.4886075949367089


In [19]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5,random_state=42,shuffle=True)
for train_index,test_index in kf.split(x):                  #for x in condition
  x_train,x_test=x[train_index],x[test_index] 
  y_train,y_test=y[train_index],y[test_index]
  knn.fit(x_train,y_train)
  y_pred=knn.predict(x_test)
  print(accuracy_score(y_test,y_pred))
  print(confusion_matrix(y_test,y_pred))
  print(classification_report(y_test,y_pred))

0.43037974683544306
[[ 8 13  2  0]
 [13 23  4  0]
 [ 2  5  3  0]
 [ 2  4  0  0]]
              precision    recall  f1-score   support

           1       0.32      0.35      0.33        23
           2       0.51      0.57      0.54        40
           3       0.33      0.30      0.32        10
           4       0.00      0.00      0.00         6

    accuracy                           0.43        79
   macro avg       0.29      0.31      0.30        79
weighted avg       0.39      0.43      0.41        79

0.4936708860759494
[[14  7  2  1]
 [11 22  2  1]
 [ 5  7  3  1]
 [ 0  2  1  0]]
              precision    recall  f1-score   support

           1       0.47      0.58      0.52        24
           2       0.58      0.61      0.59        36
           3       0.38      0.19      0.25        16
           4       0.00      0.00      0.00         3

    accuracy                           0.49        79
   macro avg       0.36      0.35      0.34        79
weighted avg       0.48 

C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capi

              precision    recall  f1-score   support

           1       0.44      0.58      0.50        19
           2       0.61      0.66      0.63        38
           3       0.17      0.14      0.15        14
           4       0.00      0.00      0.00         8

    accuracy                           0.48        79
   macro avg       0.30      0.34      0.32        79
weighted avg       0.43      0.48      0.45        79



In [20]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5,random_state=42,shuffle=True)
for train_index,test_index in kf.split(x):                  #for x in condition
  x_train,x_test=x[train_index],x[test_index] 
  y_train,y_test=y[train_index],y[test_index]
  knn.fit(x_test,y_test)
  y_pred=knn.predict(x_test)
  print(accuracy_score(y_test,y_pred))
  print(confusion_matrix(y_test,y_pred))
  print(classification_report(y_test,y_pred))

0.620253164556962
[[13  8  2  0]
 [ 8 30  2  0]
 [ 2  3  5  0]
 [ 1  4  0  1]]
              precision    recall  f1-score   support

           1       0.54      0.57      0.55        23
           2       0.67      0.75      0.71        40
           3       0.56      0.50      0.53        10
           4       1.00      0.17      0.29         6

    accuracy                           0.62        79
   macro avg       0.69      0.50      0.52        79
weighted avg       0.64      0.62      0.61        79

0.6962025316455697
[[19  5  0  0]
 [ 6 30  0  0]
 [ 3  7  6  0]
 [ 0  2  1  0]]
              precision    recall  f1-score   support

           1       0.68      0.79      0.73        24
           2       0.68      0.83      0.75        36
           3       0.86      0.38      0.52        16
           4       0.00      0.00      0.00         3

    accuracy                           0.70        79
   macro avg       0.55      0.50      0.50        79
weighted avg       0.69   

C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capi

              precision    recall  f1-score   support

           1       0.57      0.57      0.57        21
           2       0.66      0.85      0.74        41
           3       0.25      0.08      0.12        13
           4       0.00      0.00      0.00         4

    accuracy                           0.61        79
   macro avg       0.37      0.38      0.36        79
weighted avg       0.54      0.61      0.56        79

0.5822784810126582
[[12  6  1  0]
 [10 26  2  0]
 [ 1  5  8  0]
 [ 3  4  1  0]]
              precision    recall  f1-score   support

           1       0.46      0.63      0.53        19
           2       0.63      0.68      0.66        38
           3       0.67      0.57      0.62        14
           4       0.00      0.00      0.00         8

    accuracy                           0.58        79
   macro avg       0.44      0.47      0.45        79
weighted avg       0.53      0.58      0.55        79



C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Lenovo\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capi